### ISSUE TITLE
Failed to deploy cfn stack for sagemaker endpoint 

### ISSUE THREAD

**Issue by hariappi** [mk1-project/sagemaker-examples#1]
Hi, I'm trying out MK1 inference engine on sagemaker using cfn launch method from aws marketplace and seeing below error.
I dont see a way to increase quota in aws service quotas for ml.g5.2xlarge instance.

Is there something i'm missing here?

![image](https://github.com/user-attachments/assets/c3dfd9f5-c6ad-4ec7-8260-8107263bf247)

**Comment by kdmkone** [comment]
Hi @hariappi,

That's a limitation on your AWS account, you need to talk to them.
